site_name: Projeto Back-End
repo_url: https://github.com/jonh-carvalho/PBE_ADS_25.1_8001

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  color_mode: dark
  locale: pt_BR
  language: pt-BR
  favicon: images/favicon.png
  user_color_mode_toggle: true
  logo: assets/ibmec_logo.png
  features:
    - header.autohide
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.footer
    - navigation.top
    - navigation.instant
    - navigation.instant.progress

    - content.code.copy
    - content.code.select
    - content.code.annotate 
    - content.code.highlight
    - content.code.tabs
    - content.code.expand
    - content.code.extra
    - content.code.include
    - content.code.include.source
    - content.code.include.requirejs
    - content.code.include.jupyter
    - content.code.include.jupyter.execute  
    - content.code.include.jupyter.requirejs
    - content.code.include.jupyter.source 

plugins:
  - search
  - mkdocs-jupyter:
      execute: false
      include_requirejs: true
      include_source: true

extra:
  consent:
    actions:
      - accept
      - manage

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true